package main

import (
	"fmt"
	"math/rand"
)

// for computers it's hard to generate a random number
// numbers generated by coputers are pseudo random

func main() {
	guess := 10

	for n := 0; n != guess; {
		//
		n = rand.Intn(guess + 1) // rand generates pseuo random numbers
		// rand[0, n) - if we want to include n number, we have to add + 1
		fmt.Printf("%d ", n)
	}

	fmt.Println()
	// output
	// 1 1 9 3 2 4 7 6 6 6 4 0 10
	// each time when you run the program output will be exactly the same

}
