package main

import (
	"fmt"
	"math/rand"
	"time"
)

// for computers it's hard to generate a random number
// numbers generated by coputers are pseudo random

func main() {
	guess := 10

	// each time when you run the program output will be exactly the same
	// we can change it using seed
	// to provide a new number everytime when the program runs
	// we can use time in nanosecondas
	t := time.Now().UnixNano()
	rand.Seed(t) // rand.Intn depends on seed

	for n := 0; n != guess; {
		//
		n = rand.Intn(guess + 1) // rand generates pseuo random numbers
		// rand[0, n) - if we want to include n number, we have to add + 1
		fmt.Printf("%d ", n)
	}

	fmt.Println()
	// everytime you run this program the output will be different
}
